Repository olsonadr/nlp-lambdas, pull requests merged in 2022-05, with the labels that each got.

#17 Documented env vars and generally updated README
  README.md
  docs/aiid-nlp-lambdas-aws-architecture.png
  docs/example_lambdas/sentiment.py
  docs/gratuitously_detailed_explanations.md
  inference/similar.py
Labels: documentation

#18 5 testing suite
  .github/workflows/deploy_to_aws.yml
  .github/workflows/test_aws_stack.yml
  .gitignore
  README.md
  pyproject.toml
  requirements.txt
  tests/helpers/__init__.py
  tests/helpers/apitest.py
  tests/helpers/custom_exceptions.py
  tests/helpers/loop_stopper.py
  tests/helpers/testrun.py
  tests/unit/test_api_execution.py
  tests/unit/test_aws_lambdas_stack.py
  tests/unit/test_lambda_execution.py
  tests/unit/testing_materials/lambda_test_request_incident_1.json
  tests/unit/testing_materials/lamdba_bad_test_request_bad_syntax.json
  tests/unit/testing_materials/lamdba_bad_test_request_missing_input.json
  tests/unit/testing_materials/lamdba_test_request_incident_10.json
  tests/unit/testing_materials/lamdba_test_request_incident_15.json
Labels: documentation, enhancement

#21 Moved state_update.py to project root, updated README
  .github/workflows/deploy_to_aws.yml
  .github/workflows/test_aws_stack.yml
  README.md
  state_update.py
Labels: bug
